export const soorah = [
    {
      "Id": 1,
      "SurahNumber": 1,
      "AyahCount": 7,
      "StartAyahNumber": 0,
      "NameArabic": "الفاتحة",
      "NameEnglish": "Al-Faatiha",
      "NameMeaning": "The Opening",
      "Type": "Meccan",
      "RevelationOrder": 5,
      "RukuCount": 1,
      "pageIndex": 0
    },
    {
      "Id": 2,
      "SurahNumber": 2,
      "AyahCount": 286,
      "StartAyahNumber": 7,
      "NameArabic": "البقرة",
      "NameEnglish": "Al-Baqara",
      "NameMeaning": "The Cow",
      "Type": "Medinan",
      "RevelationOrder": 87,
      "RukuCount": 40,
      "pageIndex": 1
    },
    {
      "Id": 3,
      "SurahNumber": 3,
      "AyahCount": 200,
      "StartAyahNumber": 293,
      "NameArabic": "آل عمران",
      "NameEnglish": "Aal-i-Imraan",
      "NameMeaning": "The Family of Imraan",
      "Type": "Medinan",
      "RevelationOrder": 89,
      "RukuCount": 20,
      "pageIndex": 44
    },
    {
      "Id": 4,
      "SurahNumber": 4,
      "AyahCount": 176,
      "StartAyahNumber": 493,
      "NameArabic": "النساء",
      "NameEnglish": "An-Nisaa",
      "NameMeaning": "The Women",
      "Type": "Medinan",
      "RevelationOrder": 92,
      "RukuCount": 24,
      "pageIndex": 68
    },
    {
      "Id": 5,
      "SurahNumber": 5,
      "AyahCount": 120,
      "StartAyahNumber": 669,
      "NameArabic": "المائدة",
      "NameEnglish": "Al-Maaida",
      "NameMeaning": "The Table",
      "Type": "Medinan",
      "RevelationOrder": 112,
      "RukuCount": 16,
      "pageIndex": 95
    },
    {
      "Id": 6,
      "SurahNumber": 6,
      "AyahCount": 165,
      "StartAyahNumber": 789,
      "NameArabic": "الأنعام",
      "NameEnglish": "Al-An\"aam",
      "NameMeaning": "The Cattle",
      "Type": "Meccan",
      "RevelationOrder": 55,
      "RukuCount": 20,
      "pageIndex": 114
    },
    {
      "Id": 7,
      "SurahNumber": 7,
      "AyahCount": 206,
      "StartAyahNumber": 954,
      "NameArabic": "الأعراف",
      "NameEnglish": "Al-A\"raaf",
      "NameMeaning": "The Heights",
      "Type": "Meccan",
      "RevelationOrder": 39,
      "RukuCount": 24,
      "pageIndex": 135
    },
    {
      "Id": 8,
      "SurahNumber": 8,
      "AyahCount": 75,
      "StartAyahNumber": 1160,
      "NameArabic": "الأنفال",
      "NameEnglish": "Al-Anfaal",
      "NameMeaning": "The Spoils of War",
      "Type": "Medinan",
      "RevelationOrder": 88,
      "RukuCount": 10,
      "pageIndex": 158
    },
    {
      "Id": 9,
      "SurahNumber": 9,
      "AyahCount": 129,
      "StartAyahNumber": 1235,
      "NameArabic": "التوبة",
      "NameEnglish": "At-Tawba",
      "NameMeaning": "The Repentance",
      "Type": "Medinan",
      "RevelationOrder": 113,
      "RukuCount": 16,
      "pageIndex": 167
    },
    {
      "Id": 10,
      "SurahNumber": 10,
      "AyahCount": 109,
      "StartAyahNumber": 1364,
      "NameArabic": "يونس",
      "NameEnglish": "Yunus",
      "NameMeaning": "Jonas",
      "Type": "Meccan",
      "RevelationOrder": 51,
      "RukuCount": 11,
      "pageIndex": 186
    },
    {
      "Id": 11,
      "SurahNumber": 11,
      "AyahCount": 123,
      "StartAyahNumber": 1473,
      "NameArabic": "هود",
      "NameEnglish": "Hud",
      "NameMeaning": "Hud",
      "Type": "Meccan",
      "RevelationOrder": 52,
      "RukuCount": 10,
      "pageIndex": 198
    },
    {
      "Id": 12,
      "SurahNumber": 12,
      "AyahCount": 111,
      "StartAyahNumber": 1596,
      "NameArabic": "يوسف",
      "NameEnglish": "Yusuf",
      "NameMeaning": "Joseph",
      "Type": "Meccan",
      "RevelationOrder": 53,
      "RukuCount": 12,
      "pageIndex": 211
    },
    {
      "Id": 13,
      "SurahNumber": 13,
      "AyahCount": 43,
      "StartAyahNumber": 1707,
      "NameArabic": "الرعد",
      "NameEnglish": "Ar-Ra\"d",
      "NameMeaning": "The Thunder",
      "Type": "Medinan",
      "RevelationOrder": 96,
      "RukuCount": 6,
      "pageIndex": 223
    },
    {
      "Id": 14,
      "SurahNumber": 14,
      "AyahCount": 52,
      "StartAyahNumber": 1750,
      "NameArabic": "ابراهيم",
      "NameEnglish": "Ibrahim",
      "NameMeaning": "Abraham",
      "Type": "Meccan",
      "RevelationOrder": 72,
      "RukuCount": 7,
      "pageIndex": 229
    },
    {
      "Id": 15,
      "SurahNumber": 15,
      "AyahCount": 99,
      "StartAyahNumber": 1802,
      "NameArabic": "الحجر",
      "NameEnglish": "Al-Hijr",
      "NameMeaning": "The Rock",
      "Type": "Meccan",
      "RevelationOrder": 54,
      "RukuCount": 6,
      "pageIndex": 234
    },
    {
      "Id": 16,
      "SurahNumber": 16,
      "AyahCount": 128,
      "StartAyahNumber": 1901,
      "NameArabic": "النحل",
      "NameEnglish": "An-Nahl",
      "NameMeaning": "The Bee",
      "Type": "Meccan",
      "RevelationOrder": 70,
      "RukuCount": 16,
      "pageIndex": 239
    },
    {
      "Id": 17,
      "SurahNumber": 17,
      "AyahCount": 111,
      "StartAyahNumber": 2029,
      "NameArabic": "الإسراء",
      "NameEnglish": "Al-Israa",
      "NameMeaning": "The Night Journey",
      "Type": "Meccan",
      "RevelationOrder": 50,
      "RukuCount": 12,
      "pageIndex": 253
    },
    {
      "Id": 18,
      "SurahNumber": 18,
      "AyahCount": 110,
      "StartAyahNumber": 2140,
      "NameArabic": "الكهف",
      "NameEnglish": "Al-Kahf",
      "NameMeaning": "The Cave",
      "Type": "Meccan",
      "RevelationOrder": 69,
      "RukuCount": 12,
      "pageIndex": 263
    },
    {
      "Id": 19,
      "SurahNumber": 19,
      "AyahCount": 98,
      "StartAyahNumber": 2250,
      "NameArabic": "مريم",
      "NameEnglish": "Maryam",
      "NameMeaning": "Mary",
      "Type": "Meccan",
      "RevelationOrder": 44,
      "RukuCount": 6,
      "pageIndex": 274
    },
    {
      "Id": 20,
      "SurahNumber": 20,
      "AyahCount": 135,
      "StartAyahNumber": 2348,
      "NameArabic": "طه",
      "NameEnglish": "Taa-Haa",
      "NameMeaning": "Taa-Haa",
      "Type": "Meccan",
      "RevelationOrder": 45,
      "RukuCount": 8,
      "pageIndex": 280
    },
    {
      "Id": 21,
      "SurahNumber": 21,
      "AyahCount": 112,
      "StartAyahNumber": 2483,
      "NameArabic": "الأنبياء",
      "NameEnglish": "Al-Anbiyaa",
      "NameMeaning": "The Prophets",
      "Type": "Meccan",
      "RevelationOrder": 73,
      "RukuCount": 7,
      "pageIndex": 289
    },
    {
      "Id": 22,
      "SurahNumber": 22,
      "AyahCount": 78,
      "StartAyahNumber": 2595,
      "NameArabic": "الحج",
      "NameEnglish": "Al-Hajj",
      "NameMeaning": "The Pilgrimage",
      "Type": "Medinan",
      "RevelationOrder": 103,
      "RukuCount": 10,
      "pageIndex": 298
    },
    {
      "Id": 23,
      "SurahNumber": 23,
      "AyahCount": 118,
      "StartAyahNumber": 2673,
      "NameArabic": "المؤمنون",
      "NameEnglish": "Al-Muminoon",
      "NameMeaning": "The Believers",
      "Type": "Meccan",
      "RevelationOrder": 74,
      "RukuCount": 6,
      "pageIndex": 307
    },
    {
      "Id": 24,
      "SurahNumber": 24,
      "AyahCount": 64,
      "StartAyahNumber": 2791,
      "NameArabic": "النور",
      "NameEnglish": "An-Noor",
      "NameMeaning": "The Light",
      "Type": "Medinan",
      "RevelationOrder": 102,
      "RukuCount": 9,
      "pageIndex": 314
    },
    {
      "Id": 25,
      "SurahNumber": 25,
      "AyahCount": 77,
      "StartAyahNumber": 2855,
      "NameArabic": "الفرقان",
      "NameEnglish": "Al-Furqaan",
      "NameMeaning": "The Criterion",
      "Type": "Meccan",
      "RevelationOrder": 42,
      "RukuCount": 6,
      "pageIndex": 323
    },
    {
      "Id": 26,
      "SurahNumber": 26,
      "AyahCount": 227,
      "StartAyahNumber": 2932,
      "NameArabic": "الشعراء",
      "NameEnglish": "Ash-Shu\"araa",
      "NameMeaning": "The Poets",
      "Type": "Meccan",
      "RevelationOrder": 47,
      "RukuCount": 11,
      "pageIndex": 329
    },
    {
      "Id": 27,
      "SurahNumber": 27,
      "AyahCount": 93,
      "StartAyahNumber": 3159,
      "NameArabic": "النمل",
      "NameEnglish": "An-Naml",
      "NameMeaning": "The Ant",
      "Type": "Meccan",
      "RevelationOrder": 48,
      "RukuCount": 7,
      "pageIndex": 338
    },
    {
      "Id": 28,
      "SurahNumber": 28,
      "AyahCount": 88,
      "StartAyahNumber": 3252,
      "NameArabic": "القصص",
      "NameEnglish": "Al-Qasas",
      "NameMeaning": "The Stories",
      "Type": "Meccan",
      "RevelationOrder": 49,
      "RukuCount": 8,
      "pageIndex": 346
    },
    {
      "Id": 29,
      "SurahNumber": 29,
      "AyahCount": 69,
      "StartAyahNumber": 3340,
      "NameArabic": "العنكبوت",
      "NameEnglish": "Al-Ankaboot",
      "NameMeaning": "The Spider",
      "Type": "Meccan",
      "RevelationOrder": 85,
      "RukuCount": 7,
      "pageIndex": 356
    },
    {
      "Id": 30,
      "SurahNumber": 30,
      "AyahCount": 60,
      "StartAyahNumber": 3409,
      "NameArabic": "الروم",
      "NameEnglish": "Ar-Room",
      "NameMeaning": "The Romans",
      "Type": "Meccan",
      "RevelationOrder": 84,
      "RukuCount": 6,
      "pageIndex": 363
    },
    {
      "Id": 31,
      "SurahNumber": 31,
      "AyahCount": 34,
      "StartAyahNumber": 3469,
      "NameArabic": "لقمان",
      "NameEnglish": "Luqman",
      "NameMeaning": "Luqman",
      "Type": "Meccan",
      "RevelationOrder": 57,
      "RukuCount": 3,
      "pageIndex": 369
    },
    {
      "Id": 32,
      "SurahNumber": 32,
      "AyahCount": 30,
      "StartAyahNumber": 3503,
      "NameArabic": "السجدة",
      "NameEnglish": "As-Sajda",
      "NameMeaning": "The Prostration",
      "Type": "Meccan",
      "RevelationOrder": 75,
      "RukuCount": 3,
      "pageIndex": 372
    },
    {
      "Id": 33,
      "SurahNumber": 33,
      "AyahCount": 73,
      "StartAyahNumber": 3533,
      "NameArabic": "الأحزاب",
      "NameEnglish": "Al-Ahzaab",
      "NameMeaning": "The Clans",
      "Type": "Medinan",
      "RevelationOrder": 90,
      "RukuCount": 9,
      "pageIndex": 375
    },
    {
      "Id": 34,
      "SurahNumber": 34,
      "AyahCount": 54,
      "StartAyahNumber": 3606,
      "NameArabic": "سبإ",
      "NameEnglish": "Saba",
      "NameMeaning": "Sheba",
      "Type": "Meccan",
      "RevelationOrder": 58,
      "RukuCount": 6,
      "pageIndex": 384
    },
    {
      "Id": 35,
      "SurahNumber": 35,
      "AyahCount": 45,
      "StartAyahNumber": 3660,
      "NameArabic": "فاطر",
      "NameEnglish": "Faatir",
      "NameMeaning": "The Originator",
      "Type": "Meccan",
      "RevelationOrder": 43,
      "RukuCount": 5,
      "pageIndex": 390
    },
    {
      "Id": 36,
      "SurahNumber": 36,
      "AyahCount": 83,
      "StartAyahNumber": 3705,
      "NameArabic": "يس",
      "NameEnglish": "Yaseen",
      "NameMeaning": "Yaseen",
      "Type": "Meccan",
      "RevelationOrder": 41,
      "RukuCount": 5,
      "pageIndex": 395
    },
    {
      "Id": 37,
      "SurahNumber": 37,
      "AyahCount": 182,
      "StartAyahNumber": 3788,
      "NameArabic": "الصافات",
      "NameEnglish": "As-Saaffaat",
      "NameMeaning": "Those drawn up in Ranks",
      "Type": "Meccan",
      "RevelationOrder": 56,
      "RukuCount": 5,
      "pageIndex": 400
    },
    {
      "Id": 38,
      "SurahNumber": 38,
      "AyahCount": 88,
      "StartAyahNumber": 3970,
      "NameArabic": "ص",
      "NameEnglish": "Saad",
      "NameMeaning": "The letter Saad",
      "Type": "Meccan",
      "RevelationOrder": 38,
      "RukuCount": 5,
      "pageIndex": 407
    },
    {
      "Id": 39,
      "SurahNumber": 39,
      "AyahCount": 75,
      "StartAyahNumber": 4058,
      "NameArabic": "الزمر",
      "NameEnglish": "Az-Zumar",
      "NameMeaning": "The Groups",
      "Type": "Meccan",
      "RevelationOrder": 59,
      "RukuCount": 8,
      "pageIndex": 411
    },
    {
      "Id": 40,
      "SurahNumber": 40,
      "AyahCount": 85,
      "StartAyahNumber": 4133,
      "NameArabic": "المومن",
      "NameEnglish": "Al-Mo'min",
      "NameMeaning": "The Forgiver",
      "Type": "Meccan",
      "RevelationOrder": 60,
      "RukuCount": 9,
      "pageIndex": 419
    },
    {
      "Id": 41,
      "SurahNumber": 41,
      "AyahCount": 54,
      "StartAyahNumber": 4218,
      "NameArabic": "حم السجدۃ",
      "NameEnglish": "Haa Meem Sajda",
      "NameMeaning": "Explained in detail",
      "Type": "Meccan",
      "RevelationOrder": 61,
      "RukuCount": 6,
      "pageIndex": 428
    },
    {
      "Id": 42,
      "SurahNumber": 42,
      "AyahCount": 53,
      "StartAyahNumber": 4272,
      "NameArabic": "الشورى",
      "NameEnglish": "Ash-Shura",
      "NameMeaning": "Consultation",
      "Type": "Meccan",
      "RevelationOrder": 62,
      "RukuCount": 5,
      "pageIndex": 433
    },
    {
      "Id": 43,
      "SurahNumber": 43,
      "AyahCount": 89,
      "StartAyahNumber": 4325,
      "NameArabic": "الزخرف",
      "NameEnglish": "Az-Zukhruf",
      "NameMeaning": "Ornaments of gold",
      "Type": "Meccan",
      "RevelationOrder": 63,
      "RukuCount": 7,
      "pageIndex": 439
    },
    {
      "Id": 44,
      "SurahNumber": 44,
      "AyahCount": 59,
      "StartAyahNumber": 4414,
      "NameArabic": "الدخان",
      "NameEnglish": "Ad-Dukhaan",
      "NameMeaning": "The Smoke",
      "Type": "Meccan",
      "RevelationOrder": 64,
      "RukuCount": 3,
      "pageIndex": 445
    },
    {
      "Id": 45,
      "SurahNumber": 45,
      "AyahCount": 37,
      "StartAyahNumber": 4473,
      "NameArabic": "الجاثية",
      "NameEnglish": "Al-Jaathiya",
      "NameMeaning": "Crouching",
      "Type": "Meccan",
      "RevelationOrder": 65,
      "RukuCount": 4,
      "pageIndex": 447
    },
    {
      "Id": 46,
      "SurahNumber": 46,
      "AyahCount": 35,
      "StartAyahNumber": 4510,
      "NameArabic": "الأحقاف",
      "NameEnglish": "Al-Ahqaf",
      "NameMeaning": "The Dunes",
      "Type": "Meccan",
      "RevelationOrder": 66,
      "RukuCount": 4,
      "pageIndex": 451
    },
    {
      "Id": 47,
      "SurahNumber": 47,
      "AyahCount": 38,
      "StartAyahNumber": 4545,
      "NameArabic": "محمد",
      "NameEnglish": "Muhammad",
      "NameMeaning": "Muhammad",
      "Type": "Medinan",
      "RevelationOrder": 95,
      "RukuCount": 4,
      "pageIndex": 455
    },
    {
      "Id": 48,
      "SurahNumber": 48,
      "AyahCount": 29,
      "StartAyahNumber": 4583,
      "NameArabic": "الفتح",
      "NameEnglish": "Al-Fath",
      "NameMeaning": "The Victory",
      "Type": "Medinan",
      "RevelationOrder": 111,
      "RukuCount": 4,
      "pageIndex": 459
       },
    {
      "Id": 49,
      "SurahNumber": 49,
      "AyahCount": 18,
      "StartAyahNumber": 4612,
      "NameArabic": "الحجرات",
      "NameEnglish": "Al-Hujuraat",
      "NameMeaning": "The Inner Apartments",
      "Type": "Medinan",
      "RevelationOrder": 106,
      "RukuCount": 2,
      "pageIndex": 462
    },
    {
      "Id": 50,
      "SurahNumber": 50,
      "AyahCount": 45,
      "StartAyahNumber": 4630,
      "NameArabic": "ق",
      "NameEnglish": "Qaaf",
      "NameMeaning": "The letter Qaaf",
      "Type": "Meccan",
      "RevelationOrder": 34,
      "RukuCount": 3,
      "pageIndex": 465
    },
    {
      "Id": 51,
      "SurahNumber": 51,
      "AyahCount": 60,
      "StartAyahNumber": 4675,
      "NameArabic": "الذاريات",
      "NameEnglish": "Adh-Dhaariyat",
      "NameMeaning": "The Winnowing Winds",
      "Type": "Meccan",
      "RevelationOrder": 67,
      "RukuCount": 3,
      "pageIndex": 467
    },
    {
      "Id": 52,
      "SurahNumber": 52,
      "AyahCount": 49,
      "StartAyahNumber": 4735,
      "NameArabic": "الطور",
      "NameEnglish": "At-Tur",
      "NameMeaning": "The Mount",
      "Type": "Meccan",
      "RevelationOrder": 76,
      "RukuCount": 2,
      "pageIndex": 470
    },
    {
      "Id": 53,
      "SurahNumber": 53,
      "AyahCount": 62,
      "StartAyahNumber": 4784,
      "NameArabic": "النجم",
      "NameEnglish": "An-Najm",
      "NameMeaning": "The Star",
      "Type": "Meccan",
      "RevelationOrder": 23,
      "RukuCount": 3,
      "pageIndex": 472
    },
    {
      "Id": 54,
      "SurahNumber": 54,
      "AyahCount": 55,
      "StartAyahNumber": 4846,
      "NameArabic": "القمر",
      "NameEnglish": "Al-Qamar",
      "NameMeaning": "The Moon",
      "Type": "Meccan",
      "RevelationOrder": 37,
      "RukuCount": 3,
      "pageIndex": 474
    },
    {
      "Id": 55,
      "SurahNumber": 55,
      "AyahCount": 78,
      "StartAyahNumber": 4901,
      "NameArabic": "الرحمن",
      "NameEnglish": "Ar-Rahmaan",
      "NameMeaning": "The Beneficent",
      "Type": "Medinan",
      "RevelationOrder": 97,
      "RukuCount": 3,
      "pageIndex": 477
    },
    {
      "Id": 56,
      "SurahNumber": 56,
      "AyahCount": 96,
      "StartAyahNumber": 4979,
      "NameArabic": "الواقعة",
      "NameEnglish": "Al-Waaqia",
      "NameMeaning": "The Inevitable",
      "Type": "Meccan",
      "RevelationOrder": 46,
      "RukuCount": 3,
      "pageIndex": 480
    },
    {
      "Id": 57,
      "SurahNumber": 57,
      "AyahCount": 29,
      "StartAyahNumber": 5075,
      "NameArabic": "الحديد",
      "NameEnglish": "Al-Hadid",
      "NameMeaning": "The Iron",
      "Type": "Medinan",
      "RevelationOrder": 94,
      "RukuCount": 4,
      "pageIndex": 483
    },
    {
      "Id": 58,
      "SurahNumber": 58,
      "AyahCount": 22,
      "StartAyahNumber": 5104,
      "NameArabic": "المجادلة",
      "NameEnglish": "Al-Mujaadila",
      "NameMeaning": "The Pleading Woman",
      "Type": "Medinan",
      "RevelationOrder": 105,
      "RukuCount": 3,
      "pageIndex": 487
    },
    {
      "Id": 59,
      "SurahNumber": 59,
      "AyahCount": 24,
      "StartAyahNumber": 5126,
      "NameArabic": "الحشر",
      "NameEnglish": "Al-Hashr",
      "NameMeaning": "The Exile",
      "Type": "Medinan",
      "RevelationOrder": 101,
      "RukuCount": 3,
      "pageIndex": 490
    },
    {
      "Id": 60,
      "SurahNumber": 60,
      "AyahCount": 13,
      "StartAyahNumber": 5150,
      "NameArabic": "الممتحنة",
      "NameEnglish": "Al-Mumtahana",
      "NameMeaning": "She that is to be examined",
      "Type": "Medinan",
      "RevelationOrder": 91,
      "RukuCount": 2,
      "pageIndex": 494
    },
    {
      "Id": 61,
      "SurahNumber": 61,
      "AyahCount": 14,
      "StartAyahNumber": 5163,
      "NameArabic": "الصف",
      "NameEnglish": "As-Saff",
      "NameMeaning": "The Ranks",
      "Type": "Medinan",
      "RevelationOrder": 109,
      "RukuCount": 2,
      "pageIndex": 496
    },
    {
      "Id": 62,
      "SurahNumber": 62,
      "AyahCount": 11,
      "StartAyahNumber": 5177,
      "NameArabic": "الجمعة",
      "NameEnglish": "Al-Jumu\"a",
      "NameMeaning": "Friday",
      "Type": "Medinan",
      "RevelationOrder": 110,
      "RukuCount": 2,
      "pageIndex": 498
    },
    {
      "Id": 63,
      "SurahNumber": 63,
      "AyahCount": 11,
      "StartAyahNumber": 5188,
      "NameArabic": "المنافقون",
      "NameEnglish": "Al-Munaafiqoon",
      "NameMeaning": "The Hypocrites",
      "Type": "Medinan",
      "RevelationOrder": 104,
      "RukuCount": 2,
      "pageIndex": 499
    },
    {
      "Id": 64,
      "SurahNumber": 64,
      "AyahCount": 18,
      "StartAyahNumber": 5199,
      "NameArabic": "التغابن",
      "NameEnglish": "At-Taghaabun",
      "NameMeaning": "Mutual Disillusion",
      "Type": "Medinan",
      "RevelationOrder": 108,
      "RukuCount": 2,
      "pageIndex": 501
    },
    {
      "Id": 65,
      "SurahNumber": 65,
      "AyahCount": 12,
      "StartAyahNumber": 5217,
      "NameArabic": "الطلاق",
      "NameEnglish": "At-Talaaq",
      "NameMeaning": "Divorce",
      "Type": "Medinan",
      "RevelationOrder": 99,
      "RukuCount": 2,
      "pageIndex": 503
    },
    {
      "Id": 66,
      "SurahNumber": 66,
      "AyahCount": 12,
      "StartAyahNumber": 5229,
      "NameArabic": "التحريم",
      "NameEnglish": "At-Tahrim",
      "NameMeaning": "The Prohibition",
      "Type": "Medinan",
      "RevelationOrder": 107,
      "RukuCount": 2,
      "pageIndex": 505
    },
    {
      "Id": 67,
      "SurahNumber": 67,
      "AyahCount": 30,
      "StartAyahNumber": 5241,
      "NameArabic": "الملك",
      "NameEnglish": "Al-Mulk",
      "NameMeaning": "The Sovereignty",
      "Type": "Meccan",
      "RevelationOrder": 77,
      "RukuCount": 2,
      "pageIndex": 507
    },
    {
      "Id": 68,
      "SurahNumber": 68,
      "AyahCount": 52,
      "StartAyahNumber": 5271,
      "NameArabic": "القلم",
      "NameEnglish": "Al-Qalam",
      "NameMeaning": "The Pen",
      "Type": "Meccan",
      "RevelationOrder": 2,
      "RukuCount": 2,
      "pageIndex": 509
    },
    {
      "Id": 69,
      "SurahNumber": 69,
      "AyahCount": 52,
      "StartAyahNumber": 5323,
      "NameArabic": "الحاقة",
      "NameEnglish": "Al-Haaqqa",
      "NameMeaning": "The Reality",
      "Type": "Meccan",
      "RevelationOrder": 78,
      "RukuCount": 2,
      "pageIndex": 511
    },
    {
      "Id": 70,
      "SurahNumber": 70,
      "AyahCount": 44,
      "StartAyahNumber": 5375,
      "NameArabic": "المعارج",
      "NameEnglish": "Al-Ma\"aarij",
      "NameMeaning": "The Ascending Stairways",
      "Type": "Meccan",
      "RevelationOrder": 79,
      "RukuCount": 2,
      "pageIndex": 513
    },
    {
      "Id": 71,
      "SurahNumber": 71,
      "AyahCount": 28,
      "StartAyahNumber": 5419,
      "NameArabic": "نوح",
      "NameEnglish": "Nooh",
      "NameMeaning": "Noah",
      "Type": "Meccan",
      "RevelationOrder": 71,
      "RukuCount": 2,
      "pageIndex": 515
    },
    {
      "Id": 72,
      "SurahNumber": 72,
      "AyahCount": 28,
      "StartAyahNumber": 5447,
      "NameArabic": "الجن",
      "NameEnglish": "Al-Jinn",
      "NameMeaning": "The Jinn",
      "Type": "Meccan",
      "RevelationOrder": 40,
      "RukuCount": 2,
      "pageIndex": 517
    },
    {
      "Id": 73,
      "SurahNumber": 73,
      "AyahCount": 20,
      "StartAyahNumber": 5475,
      "NameArabic": "المزمل",
      "NameEnglish": "Al-Muzzammil",
      "NameMeaning": "The Enshrouded One",
      "Type": "Meccan",
      "RevelationOrder": 3,
      "RukuCount": 2,
      "pageIndex": 519
    },
    {
      "Id": 74,
      "SurahNumber": 74,
      "AyahCount": 56,
      "StartAyahNumber": 5495,
      "NameArabic": "المدثر",
      "NameEnglish": "Al-Muddaththir",
      "NameMeaning": "The Cloaked One",
      "Type": "Meccan",
      "RevelationOrder": 4,
      "RukuCount": 2,
      "pageIndex": 520
    },
    {
      "Id": 75,
      "SurahNumber": 75,
      "AyahCount": 40,
      "StartAyahNumber": 5551,
      "NameArabic": "القيامة",
      "NameEnglish": "Al-Qiyaama",
      "NameMeaning": "The Resurrection",
      "Type": "Meccan",
      "RevelationOrder": 31,
      "RukuCount": 2,
      "pageIndex": 522
    },
    {
      "Id": 76,
      "SurahNumber": 76,
      "AyahCount": 31,
      "StartAyahNumber": 5591,
      "NameArabic": "الدھر",
      "NameEnglish": "Al-Dahr",
      "NameMeaning": "",
      "Type": "Medinan",
      "RevelationOrder": 98,
      "RukuCount": 2,
      "pageIndex": 523
    },
    {
      "Id": 77,
      "SurahNumber": 77,
      "AyahCount": 50,
      "StartAyahNumber": 5622,
      "NameArabic": "المرسلات",
      "NameEnglish": "Al-Mursalaat",
      "NameMeaning": "The Emissaries",
      "Type": "Meccan",
      "RevelationOrder": 33,
      "RukuCount": 2,
      "pageIndex": 525
    },
    {
      "Id": 78,
      "SurahNumber": 78,
      "AyahCount": 40,
      "StartAyahNumber": 5672,
      "NameArabic": "النبإ",
      "NameEnglish": "An-Naba",
      "NameMeaning": "The Announcement",
      "Type": "Meccan",
      "RevelationOrder": 80,
      "RukuCount": 2,
      "pageIndex": 527
    },
    {
      "Id": 79,
      "SurahNumber": 79,
      "AyahCount": 46,
      "StartAyahNumber": 5712,
      "NameArabic": "النازعات",
      "NameEnglish": "An-Naazi\"aat",
      "NameMeaning": "Those who drag forth",
      "Type": "Meccan",
      "RevelationOrder": 81,
      "RukuCount": 2,
      "pageIndex": 528
    },
    {
      "Id": 80,
      "SurahNumber": 80,
      "AyahCount": 42,
      "StartAyahNumber": 5758,
      "NameArabic": "عبس",
      "NameEnglish": "Abasa",
      "NameMeaning": "He frowned",
      "Type": "Meccan",
      "RevelationOrder": 24,
      "RukuCount": 1,
      "pageIndex": 529
    },
    {
      "Id": 81,
      "SurahNumber": 81,
      "AyahCount": 29,
      "StartAyahNumber": 5800,
      "NameArabic": "التكوير",
      "NameEnglish": "At-Takwir",
      "NameMeaning": "The Overthrowing",
      "Type": "Meccan",
      "RevelationOrder": 7,
      "RukuCount": 1,
      "pageIndex": 531
    },
    {
      "Id": 82,
      "SurahNumber": 82,
      "AyahCount": 19,
      "StartAyahNumber": 5829,
      "NameArabic": "الإنفطار",
      "NameEnglish": "Al-Infitaar",
      "NameMeaning": "The Cleaving",
      "Type": "Meccan",
      "RevelationOrder": 82,
      "RukuCount": 1,
      "pageIndex": 531
    },
    {
      "Id": 83,
      "SurahNumber": 83,
      "AyahCount": 36,
      "StartAyahNumber": 5848,
      "NameArabic": "المطففين",
      "NameEnglish": "Al-Mutaffifin",
      "NameMeaning": "Defrauding",
      "Type": "Meccan",
      "RevelationOrder": 86,
      "RukuCount": 1,
      "pageIndex": 532
    },
    {
      "Id": 84,
      "SurahNumber": 84,
      "AyahCount": 25,
      "StartAyahNumber": 5884,
      "NameArabic": "الإنشقاق",
      "NameEnglish": "Al-Inshiqaaq",
      "NameMeaning": "The Splitting Open",
      "Type": "Meccan",
      "RevelationOrder": 83,
      "RukuCount": 1,
      "pageIndex": 533
    },
    {
      "Id": 85,
      "SurahNumber": 85,
      "AyahCount": 22,
      "StartAyahNumber": 5909,
      "NameArabic": "البروج",
      "NameEnglish": "Al-Burooj",
      "NameMeaning": "The Constellations",
      "Type": "Meccan",
      "RevelationOrder": 27,
      "RukuCount": 1,
      "pageIndex": 534
    },
    {
      "Id": 86,
      "SurahNumber": 86,
      "AyahCount": 17,
      "StartAyahNumber": 5931,
      "NameArabic": "الطارق",
      "NameEnglish": "At-Taariq",
      "NameMeaning": "The Morning Star",
      "Type": "Meccan",
      "RevelationOrder": 36,
      "RukuCount": 1,
      "pageIndex": 535
    },
    {
      "Id": 87,
      "SurahNumber": 87,
      "AyahCount": 19,
      "StartAyahNumber": 5948,
      "NameArabic": "الأعلى",
      "NameEnglish": "Al-A\"laa",
      "NameMeaning": "The Most High",
      "Type": "Meccan",
      "RevelationOrder": 8,
      "RukuCount": 1,
      "pageIndex": 536
    },
    {
      "Id": 88,
      "SurahNumber": 88,
      "AyahCount": 26,
      "StartAyahNumber": 5967,
      "NameArabic": "الغاشية",
      "NameEnglish": "Al-Ghaashiya",
      "NameMeaning": "The Overwhelming",
      "Type": "Meccan",
      "RevelationOrder": 68,
      "RukuCount": 1,
      "pageIndex": 536
    },
    {
      "Id": 89,
      "SurahNumber": 89,
      "AyahCount": 30,
      "StartAyahNumber": 5993,
      "NameArabic": "الفجر",
      "NameEnglish": "Al-Fajr",
      "NameMeaning": "The Dawn",
      "Type": "Meccan",
      "RevelationOrder": 10,
      "RukuCount": 1,
      "pageIndex": 537
    },
    {
      "Id": 90,
      "SurahNumber": 90,
      "AyahCount": 20,
      "StartAyahNumber": 6023,
      "NameArabic": "البلد",
      "NameEnglish": "Al-Balad",
      "NameMeaning": "The City",
      "Type": "Meccan",
      "RevelationOrder": 35,
      "RukuCount": 1,
      "pageIndex": 538
    },
    {
      "Id": 91,
      "SurahNumber": 91,
      "AyahCount": 15,
      "StartAyahNumber": 6043,
      "NameArabic": "الشمس",
      "NameEnglish": "Ash-Shams",
      "NameMeaning": "The Sun",
      "Type": "Meccan",
      "RevelationOrder": 26,
      "RukuCount": 1,
      "pageIndex": 539
    },
    {
      "Id": 92,
      "SurahNumber": 92,
      "AyahCount": 21,
      "StartAyahNumber": 6058,
      "NameArabic": "الليل",
      "NameEnglish": "Al-Lail",
      "NameMeaning": "The Night",
      "Type": "Meccan",
      "RevelationOrder": 9,
      "RukuCount": 1,
      "pageIndex": 539
    },
    {
      "Id": 93,
      "SurahNumber": 93,
      "AyahCount": 11,
      "StartAyahNumber": 6079,
      "NameArabic": "الضحى",
      "NameEnglish": "Ad-Dhuhaa",
      "NameMeaning": "The Morning Hours",
      "Type": "Meccan",
      "RevelationOrder": 11,
      "RukuCount": 1,
      "pageIndex": 540
    },
    {
      "Id": 94,
      "SurahNumber": 94,
      "AyahCount": 8,
      "StartAyahNumber": 6090,
      "NameArabic": "الشرح",
      "NameEnglish": "Ash-Sharh",
      "NameMeaning": "The Consolation",
      "Type": "Meccan",
      "RevelationOrder": 12,
      "RukuCount": 1,
      "pageIndex": 540
    },
    {
      "Id": 95,
      "SurahNumber": 95,
      "AyahCount": 8,
      "StartAyahNumber": 6098,
      "NameArabic": "التين",
      "NameEnglish": "At-Tin",
      "NameMeaning": "The Fig",
      "Type": "Meccan",
      "RevelationOrder": 28,
      "RukuCount": 1,
      "pageIndex": 541
    },
    {
      "Id": 96,
      "SurahNumber": 96,
      "AyahCount": 19,
      "StartAyahNumber": 6106,
      "NameArabic": "العلق",
      "NameEnglish": "Al-Alaq",
      "NameMeaning": "The Clot",
      "Type": "Meccan",
      "RevelationOrder": 1,
      "RukuCount": 1,
      "pageIndex": 541
    },
    {
      "Id": 97,
      "SurahNumber": 97,
      "AyahCount": 5,
      "StartAyahNumber": 6125,
      "NameArabic": "القدر",
      "NameEnglish": "Al-Qadr",
      "NameMeaning": "The Power, Fate",
      "Type": "Meccan",
      "RevelationOrder": 25,
      "RukuCount": 1,
      "pageIndex": 542
    },
    {
      "Id": 98,
      "SurahNumber": 98,
      "AyahCount": 8,
      "StartAyahNumber": 6130,
      "NameArabic": "البينة",
      "NameEnglish": "Al-Bayyina",
      "NameMeaning": "The Evidence",
      "Type": "Medinan",
      "RevelationOrder": 100,
      "RukuCount": 1,
      "pageIndex": 542
    },
    {
      "Id": 99,
      "SurahNumber": 99,
      "AyahCount": 8,
      "StartAyahNumber": 6138,
      "NameArabic": "الزلزلة",
      "NameEnglish": "Az-Zalzala",
      "NameMeaning": "The Earthquake",
      "Type": "Medinan",
      "RevelationOrder": 93,
      "RukuCount": 1,
      "pageIndex": 543
    },
    {
      "Id": 100,
      "SurahNumber": 100,
      "AyahCount": 11,
      "StartAyahNumber": 6146,
      "NameArabic": "العاديات",
      "NameEnglish": "Al-Aadiyaat",
      "NameMeaning": "The Chargers",
      "Type": "Meccan",
      "RevelationOrder": 14,
      "RukuCount": 1,
      "pageIndex": 543
    },
    {
      "Id": 101,
      "SurahNumber": 101,
      "AyahCount": 11,
      "StartAyahNumber": 6157,
      "NameArabic": "القارعة",
      "NameEnglish": "Al-Qaari\"a",
      "NameMeaning": "The Calamity",
      "Type": "Meccan",
      "RevelationOrder": 30,
      "RukuCount": 1,
      "pageIndex": 543
    },
    {
      "Id": 102,
      "SurahNumber": 102,
      "AyahCount": 8,
      "StartAyahNumber": 6168,
      "NameArabic": "التكاثر",
      "NameEnglish": "At-Takaathur",
      "NameMeaning": "Competition",
      "Type": "Meccan",
      "RevelationOrder": 16,
      "RukuCount": 1,
      "pageIndex": 544
    },
    {
      "Id": 103,
      "SurahNumber": 103,
      "AyahCount": 3,
      "StartAyahNumber": 6176,
      "NameArabic": "العصر",
      "NameEnglish": "Al-Asr",
      "NameMeaning": "The Declining Day, Epoch",
      "Type": "Meccan",
      "RevelationOrder": 13,
      "RukuCount": 1,
      "pageIndex": 544
    },
    {
      "Id": 104,
      "SurahNumber": 104,
      "AyahCount": 9,
      "StartAyahNumber": 6179,
      "NameArabic": "الهمزة",
      "NameEnglish": "Al-Humaza",
      "NameMeaning": "The Traducer",
      "Type": "Meccan",
      "RevelationOrder": 32,
      "RukuCount": 1,
      "pageIndex": 544
    },
    {
      "Id": 105,
      "SurahNumber": 105,
      "AyahCount": 5,
      "StartAyahNumber": 6188,
      "NameArabic": "الفيل",
      "NameEnglish": "Al-Fil",
      "NameMeaning": "The Elephant",
      "Type": "Meccan",
      "RevelationOrder": 19,
      "RukuCount": 1,
      "pageIndex": 545
    },
    {
      "Id": 106,
      "SurahNumber": 106,
      "AyahCount": 4,
      "StartAyahNumber": 6193,
      "NameArabic": "قريش",
      "NameEnglish": "Quraish",
      "NameMeaning": "Quraysh",
      "Type": "Meccan",
      "RevelationOrder": 29,
      "RukuCount": 1,
      "pageIndex": 545
    },
    {
      "Id": 107,
      "SurahNumber": 107,
      "AyahCount": 7,
      "StartAyahNumber": 6197,
      "NameArabic": "الماعون",
      "NameEnglish": "Al-Maa\"un",
      "NameMeaning": "Almsgiving",
      "Type": "Meccan",
      "RevelationOrder": 17,
      "RukuCount": 1,
      "pageIndex": 545
    },
    {
      "Id": 108,
      "SurahNumber": 108,
      "AyahCount": 3,
      "StartAyahNumber": 6204,
      "NameArabic": "الكوثر",
      "NameEnglish": "Al-Kawthar",
      "NameMeaning": "Abundance",
      "Type": "Meccan",
      "RevelationOrder": 15,
      "RukuCount": 1,
      "pageIndex": 546
    },
    {
      "Id": 109,
      "SurahNumber": 109,
      "AyahCount": 6,
      "StartAyahNumber": 6207,
      "NameArabic": "الكافرون",
      "NameEnglish": "Al-Kaafiroon",
      "NameMeaning": "The Disbelievers",
      "Type": "Meccan",
      "RevelationOrder": 18,
      "RukuCount": 1,
      "pageIndex": 546
    },
    {
      "Id": 110,
      "SurahNumber": 110,
      "AyahCount": 3,
      "StartAyahNumber": 6213,
      "NameArabic": "النصر",
      "NameEnglish": "An-Nasr",
      "NameMeaning": "Divine Support",
      "Type": "Medinan",
      "RevelationOrder": 114,
      "RukuCount": 1,
      "pageIndex": 546
    },
    {
      "Id": 111,
      "SurahNumber": 111,
      "AyahCount": 5,
      "StartAyahNumber": 6216,
      "NameArabic": "المسد",
      "NameEnglish": "Al-Masad",
      "NameMeaning": "The Palm Fibre",
      "Type": "Meccan",
      "RevelationOrder": 6,
      "RukuCount": 1,
      "pageIndex": 546
    },
    {
      "Id": 112,
      "SurahNumber": 112,
      "AyahCount": 4,
      "StartAyahNumber": 6221,
      "NameArabic": "الإخلاص",
      "NameEnglish": "Al-Ikhlaas",
      "NameMeaning": "Sincerity",
      "Type": "Meccan",
      "RevelationOrder": 22,
      "RukuCount": 1,
      "pageIndex": 547
    },
    {
      "Id": 113,
      "SurahNumber": 113,
      "AyahCount": 5,
      "StartAyahNumber": 6225,
      "NameArabic": "الفلق",
      "NameEnglish": "Al-Falaq",
      "NameMeaning": "The Dawn",
      "Type": "Meccan",
      "RevelationOrder": 20,
      "RukuCount": 1,
      "pageIndex": 547
    },
    {
      "Id": 114,
      "SurahNumber": 114,
      "AyahCount": 6,
      "StartAyahNumber": 6230,
      "NameArabic": "الناس",
      "NameEnglish": "An-Naas",
      "NameMeaning": "Mankind",
      "Type": "Meccan",
      "RevelationOrder": 21,
      "RukuCount": 1,
      "pageIndex": 547
    }
   ]